### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by deepakrakh** [Piashsarker/AndroidAppUpdateLibrary#12]
java.io.FileNotFoundException: https://github.com/Piashsarker/AndroidAppUpdateLibrary/raw/master/app-debug.apk
2021-01-04 15:38:07.086 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
2021-01-04 15:38:07.086 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
2021-01-04 15:38:07.086 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
2021-01-04 15:38:07.087 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at com.dcastalia.localappupdate.DownloadApk$DownloadNewVersion.doInBackground(DownloadApk.java:133)
2021-01-04 15:38:07.088 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at com.dcastalia.localappupdate.DownloadApk$DownloadNewVersion.doInBackground(DownloadApk.java:54)
2021-01-04 15:38:07.088 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2021-01-04 15:38:07.088 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-01-04 15:38:07.089 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2021-01-04 15:38:07.089 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2021-01-04 15:38:07.089 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2021-01-04 15:38:07.089 7420-7468/com.netsurf.ajaybiotechtest W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by midou221** [comment]
same here..
any solutions??

**Comment by cyb3rko** [comment]
@deepakrakh @midou221 Which Android version you tried this on?

**Comment by Piashsarker** [comment]
@cyb3rko  can we close this issue?

**Comment by cyb3rko** [comment]
Not quite sure if this issue was due to using higher Android versions.
@deepakrakh or @midou221 would have to test it out.

**Comment by midou221** [comment]
@cyb3rko  im using android 8
@Piashsarker You can close because i switched to another library

**Comment by cyb3rko** [comment]
@midou221 
For me it works with Android 8.
Could you provide us with some more details to reproduce it?

Have you tried the sample app or is it your own project?
I updated many things, you can try it out with the new version of this library.

@Piashsarker Leave it open to fix it at some point

**Comment by h0jeZvgoxFepBQ2C** [comment]
@midou221 to which library did you switch?

**Comment by cyb3rko** [comment]
@h0jeZvgoxFepBQ2C Does the update still not work for you?
Because we added the compatibility with higher Android versions.

**Comment by Piashsarker** [comment]
Closing this issue as the details is not provided.
