### ISSUE TITLE
open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by vse3211** [Piashsarker/AndroidAppUpdateLibrary#27]
```
2023-09-12 22:56:12.570  9801-9934  System.err              kz.aocorp.ailoader                   W  java.io.FileNotFoundException: /storage/emulated/0/Download/ailoaderupdate.apk: open failed: EACCES (Permission denied)
2023-09-12 22:56:12.570  9801-9934  System.err              kz.aocorp.ailoader                   W  	at libcore.io.IoBridge.open(IoBridge.java:496)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at com.dcastalia.localappupdate.DownloadApk$DownloadNewVersion.doInBackground(DownloadApk.kt:101)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at com.dcastalia.localappupdate.DownloadApk$DownloadNewVersion.doInBackground(DownloadApk.kt:36)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at android.os.AsyncTask$3.call(AsyncTask.java:378)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at java.lang.Thread.run(Thread.java:919)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at libcore.io.Linux.open(Native Method)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	at libcore.io.IoBridge.open(IoBridge.java:482)
2023-09-12 22:56:12.571  9801-9934  System.err              kz.aocorp.ailoader                   W  	... 10 more
```

I grant all permissions on AndroidManifest and in code

```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

```
if (checkSelfPermission(android.Manifest.permission.READ_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED) {
            val url = "https://github.com/Piashsarker/AndroidAppUpdateLibrary/raw/master/app-debug.apk"

            val downloadApk = DownloadApk(this)
            downloadApk.startDownloadingApk(url, "ailoaderupdate")
        } else {
            requestPermissions(arrayOf(android.Manifest.permission.READ_EXTERNAL_STORAGE), 32241)
        }
```

**Comment by Piashsarker** [comment]
Are you trying to download and install it in emulator ? Plese provide more specific information about your device and android version. thanks
