### ISSUE TITLE
leaked window

### ISSUE THREAD

**Issue by nowfalsalahudeen** [Piashsarker/AndroidAppUpdateLibrary#3]
ndroid.view.WindowLeaked: Activity com.storyz.live.livetv.MainActivity has leaked window DecorView@dae4025[] that was originally added here

this error after app updates

**Comment by Piashsarker** [comment]
This might be issue for your APK or For Your Source Code Related. Try To add full logcat here may be i can help

**Comment by Piashsarker** [comment]
Activity `com.storyz.live.livetv.MainActivity` definitely this is your activity. This activity doesn't belong to my library. So please check your code and let me know.

**Comment by nowfalsalahudeen** [comment]
yep..myActivity is mine ..this error probably occure in your downloading progress dialog..dialog closed not properly.after update done toast.current apk closes immediatly..and never it reopen

**Comment by nowfalsalahudeen** [comment]
E/WindowManager: android.view.WindowLeaked: Activity com.storyz.live.livetv.MainActivity has leaked window DecorView@d5a8cb0[] that was originally added here
                                                                         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
                                                                         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
                                                                         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                         at android.app.Dialog.show(Dialog.java:330)
                                                                         at com.dcastalia.localappupdate.DownloadApk$DownloadNewVersion.onPreExecute(DownloadApk.java:65)
                                                                         at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:648)
                                                                         at android.os.AsyncTask.execute(AsyncTask.java:595)
                                                                         at com.dcastalia.localappupdate.DownloadApk.startDownloadingApk(DownloadApk.java:44)
                                                                         at com.storyz.live.livetv.MainActivity.downloadTask(MainActivity.java:617)
                                                                         at com.storyz.live.livetv.MainActivity.checkWriteExternalStoragePermission(MainActivity.java:576)
                                                                         at com.storyz.live.livetv.MainActivity.download(MainActivity.java:605)
                                                                         at com.storyz.live.livetv.MainActivity$3.done(MainActivity.java:165)
                                                                         at com.storyz.live.livetv.MainActivity$3.done(MainActivity.java:145)
                                                                         at com.parse.ParseTaskUtils$2$1.run(ParseTaskUtils.java:116)
                                                                         at android.os.Handler.handleCallback(Handler.java:790)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Piashsarker** [comment]
@nowfalsalahudeen  Will you please share your uses code.

**Comment by nowfalsalahudeen** [comment]
and also it doesnt update app to newer version

**Comment by nowfalsalahudeen** [comment]
```
try {
                            pInfo = MainActivity.this.getPackageManager().getPackageInfo(getPackageName(), 0);
                            String version = pInfo.versionName;
                        } catch (PackageManager.NameNotFoundException ee) {
                            ee.printStackTrace();
                        }

                        int verCode = pInfo.versionCode;
                        System.out.println("version code "+verCode);
                        if(object.getInt("verCode") > verCode){
                            Toast.makeText(MainActivity.this, "New Update Available..Please grant storage permission to install new update", Toast.LENGTH_LONG).show();

                            String url = object.getString("apk_link");
                            updateAPKlink = url;

                            download();
                        }




public void download() {
        /** First check the external storage permission.**/
        checkWriteExternalStoragePermission();
    }

    private void downloadTask() {
        /** This @DownloadApk class is provided by our Library **/
        /** Pass the  Context when creating object of DownlodApk **
         */

        DownloadApk downloadApk = new DownloadApk(MainActivity.this);

        /** For Starting download call the method startDownLoadingApk() by passing the URL **/
            downloadApk.startDownloadingApk(updateAPKlink);
//
    }

```

all other runtime permission codes are same as yours demo code

**Comment by Piashsarker** [comment]
Add new version dependencies in your gradle file  : `compile 'com.github.Piashsarker:AndroidAppUpdateLibrary:1.0.1'`

Let me know if the problem is solved or not.

**Comment by Piashsarker** [comment]
@nowfalsalahudeen  For updating your existing apk , please make sure  your package name are same and also double check your apk that you are trying to download.
